version: "3"
services:
    mongo:
        image: mongo
        volumes:
            - ./mongodb-data:/data/db
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express
        depends_on:
            - mongo
        ports:
            - 8081:8081
        restart: always
